version: 2.1
jobs:
    build:
        docker:
           - image: python:3.7.3-stretch
        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-deps-{{ checksum "requirements.txt" }}
                  - v1-deps-
            - run:
                name: Installing Dependencies
                command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  make install
                  wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                  chmod +x /bin/hadolint
            - save_cache:
                  paths:
                    - ./venv
                  key: v1-deps-{{  checksum "requirements.txt"  }}

            - run:
                name: Lint
                command: |
                    . venv/bin/activate
                    make lint

workflows:
  Build:
    jobs:
      - build
